spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://49.232.228.221:3306/potucs?serverTimezone=GMT&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver


#showSql
logging:
  level:
    com:
      example:
        mapper : debug

#mybatis
mybatis:
  mapper-locations: classpath*:com/potucs/mapper/*Mapper.xml

